"""Initial migration with DSIRE database

Revision ID: 1fd1ae9a396a
Revises: 
Create Date: 2025-08-09 00:40:31.303578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd1ae9a396a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dsire_state_program_parameters')
    op.drop_table('dsire_federal_programs_backup')
    with op.batch_alter_table('dsire_federal_programs', schema=None) as batch_op:
        batch_op.drop_column('tax_credit_percentage')

    with op.batch_alter_table('dsire_state_programs', schema=None) as batch_op:
        batch_op.drop_column('tax_credit_percentage')

    with op.batch_alter_table('vehicle_mpg', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_mpg', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('dsire_state_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_credit_percentage', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('dsire_federal_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_credit_percentage', sa.FLOAT(), nullable=True))

    op.create_table('dsire_federal_programs_backup',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('dsire_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('category', sa.TEXT(), nullable=True),
    sa.Column('program_type', sa.TEXT(), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('website_url', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.NUMERIC(), nullable=True),
    sa.Column('created_at', sa.NUMERIC(), nullable=True),
    sa.Column('credibility_boost', sa.NUMERIC(), nullable=True),
    sa.Column('incentive_amount', sa.REAL(), nullable=True),
    sa.Column('tax_credit_percentage', sa.REAL(), nullable=True),
    sa.Column('percent_of_cost', sa.REAL(), nullable=True),
    sa.Column('percent_of_cost_cap', sa.REAL(), nullable=True),
    sa.Column('per_unit_rate', sa.REAL(), nullable=True),
    sa.Column('per_unit_type', sa.TEXT(), nullable=True),
    sa.Column('min_system_size_kw', sa.REAL(), nullable=True),
    sa.Column('max_system_size_kw', sa.REAL(), nullable=True),
    sa.Column('min_project_cost', sa.REAL(), nullable=True),
    sa.Column('incentive_summary', sa.TEXT(), nullable=True)
    )
    op.create_table('dsire_state_program_parameters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('program_id', sa.INTEGER(), nullable=False),
    sa.Column('parameter_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.VARCHAR(length=50), nullable=True),
    sa.Column('units', sa.VARCHAR(length=20), nullable=True),
    sa.Column('qualifier', sa.VARCHAR(length=50), nullable=True),
    sa.Column('raw_data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['dsire_state_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
